# Generated by Django 4.0.5 on 2022-07-19 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='articles',
        ),
    ]
