# Generated by Django 4.0.5 on 2022-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid_advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=500)),
                ('text', models.TextField(max_length=300)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
