# Generated by Django 4.0.5 on 2022-07-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_paid_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_advertising',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
