# Generated by Django 3.2.5 on 2022-08-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_paid_advertising_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_bot', to='index_page.categories'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chats',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_chat', to='index_page.categories'),
        ),
    ]
