# Generated by Django 3.2.5 on 2022-08-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0006_auto_20220816_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_channel', to='index_page.categories'),
        ),
    ]
