# Generated by Django 3.2.5 on 2022-08-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0007_alter_channels_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='category',
        ),
    ]
